runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  GCS_BUCKET: 'rehabstudio-gallery-169522.appspot.com'

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest